### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by yuchonghua** [easyboot/easyboot.github.com#1]
感谢

**Comment by yuchonghua** [comment]
@easyboot 您好

**Comment by easyboot** [comment]
this is my test web project，it's simple  example！Sent from my Huawei phone-------- Original message --------From: 桦 <notifications@github.com>Date: Tue, Jan 19, 2021, 10:12To: easyboot/outdoor <outdoor@noreply.github.com>Cc: easyboot <easyboot@aliyun.com>, Mention <mention@noreply.github.com>Subject: Re: [easyboot/outdoor] Hello, I am looking forward to using easyboot to develop a project. Can you give me some permissions for easyboot? Thank you (#1)

@easyboot 您好

**Comment by yuchonghua** [comment]
@easyboot 我想使用easyboot 这个名字创建一个账号，您方便把easyboot贡献给我吗？

非常感谢

如果可以的话，步骤如下：
1、打开：https://github.com/settings/admin
2、点击“Change username”
3、输入新的账号名称
